<a href="https://colab.research.google.com/github/chrispi21/ml-bc/blob/main/unsupervised/02_dimensionality_reduction/03_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Podział na zbiór treningowy i testowy](#2)
4. [Standaryzacja](#3)
5. [PCA](#4)




### <a name='0'></a> Import bibliotek

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

### <a name='1'></a> Załadowanie danych

In [2]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
data = df.iloc[:, 1:]
target = df.iloc[:, 0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
target.value_counts()

0
2    71
1    59
3    48
Name: count, dtype: int64

### <a name='2'></a> Podział na zbiór treningowy i testowy

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (133, 13)
X_test shape: (45, 13)


### <a name='3'></a> Standaryzacja

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]

array([[-0.5524, -0.8682, -1.7499, -0.3132, -0.7892, -1.3433, -0.6963, -0.5729, -0.4623, -1.1497,  0.3186,  0.1972, -0.6193],
       [ 1.0483, -0.5458, -0.9008, -1.0718,  0.1109,  1.2528,  1.3182, -1.2355,  0.9633,  0.3971, -0.2491,  1.011 ,  0.7289],
       [ 0.1371,  1.2463, -0.785 ,  0.4453,  0.1801, -1.2646, -1.5001,  0.5866, -0.5525, -0.4929, -1.6027, -1.3868,  0.2348],
       [-0.4416, -0.6881, -0.3604,  0.3543, -1.3431, -1.4534, -0.5971,  1.829 ,  0.025 , -0.8954, -0.0307, -0.8345, -0.8329],
       [ 0.5681, -0.432 ,  1.1449, -0.1615,  0.734 ,  0.0728,  0.4648, -0.5729, -0.1194, -0.4081,  0.5806,  0.3425,  1.0795]])

### <a name='4'></a> PCA

In [7]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

Wyjaśniona wariancja

In [9]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulative'] = results['explained_variance_ratio'].cumsum()
results['component'] = results.index + 1
results

explained_variance_ratio  cumulative  component
0                  0.367373    0.367373          1
1                  0.192359    0.559732          2
2                  0.099866    0.659598          3

In [10]:
fig = go.Figure(data=[go.Bar(x=results['component'], y=results['explained_variance_ratio'], name='explained variance ratio'),
                      go.Scatter(x=results['component'], y=results['cumulative'], name='cumulative explained variance')],
                layout=go.Layout(title=f'PCA - {pca.n_components_} components', width=950, template='plotly_dark'))
fig.show()

In [11]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca1', 'pca2', 'pca3', 'target'])
X_train_pca_df.head()

pca1      pca2      pca3  target
0 -0.515641 -2.379469 -1.574942     2.0
1  2.784247  0.645775 -1.142382     1.0
2 -2.684432  0.487644 -1.111007     3.0
3 -2.005767 -1.590140  0.014181     2.0
4  1.297366  0.729303  0.654154     1.0

In [12]:
px.scatter_3d(X_train_pca_df, x='pca1', y='pca2', z='pca3', color='target', template='plotly_dark', width=950)

In [13]:
X_train_pca[:5]

array([[-0.5156, -2.3795, -1.5749],
       [ 2.7842,  0.6458, -1.1424],
       [-2.6844,  0.4876, -1.111 ],
       [-2.0058, -1.5901,  0.0142],
       [ 1.2974,  0.7293,  0.6542]])

In [14]:
X_test_pca[:5]

array([[-0.5412, -2.2356, -0.5774],
       [-0.7615, -3.1408, -4.5867],
       [ 1.735 ,  1.6495,  1.5211],
       [-3.4863,  2.2006, -0.458 ],
       [ 2.396 ,  1.2113, -0.7517]])